### ISSUE TITLE
App freezes when tapping on a profile's picture/banner

### ISSUE THREAD

**Issue by trisrc** [feditext/feditext#106]
**Describe the bug**
The app freezes whenever tapping on a user's profile picture or banner.

**To Reproduce**
1. Visit any user profile
2. Tap on their profile picture or banner
3. Freeze achieved

**Expected behavior**
Getting a full view of the user's profile picture/banner that was tapped on.

**(please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 17.0 (21A5277j)
 - App Version 1.7.2 (56)

**Comment by rrgeorge** [comment]
I’m also experiencing this on iOS 16.5.1

**Comment by VyrCossont** [comment]
Easiest repro ever. Thanks for the reports, let's see what went wrong here.

**Comment by bdube** [comment]
I tried some debugging last night, but ran out of time. The last thing I would see was a height constraint violation in a UIStackView. This message displays before I tap on the profile image, though, and nothing more displays after I tap.

**Comment by VyrCossont** [comment]
Looks like I introduced this bug with 7ae4eb722288d60eb5931c0d0a37320ad32b8fd2, which had to touch the code used to display image attachments, which is apparently also the code used to display avatars and headers. Reverting to f644b758c787ae12c324b6673e1c1cf049b2f32e, the commit before that, restores the functionality. There's a code path in (at least) `ImageViewController.viewDidLoad` that would not be used by image attachments but is used by avatars and headers, and I suspect this is related.

**Comment by VyrCossont** [comment]
Also, there are so many underconstrained views in this codebase that I don't think we're going to get rid of those messages any time soon and with any effort much short of what it'd take to do a SwiftUI conversion. So those messages are unfortunately not terribly useful, although the purple ⚠️ icons in the view hierarchy debugger will at least tell you which components they affect.

**Comment by VyrCossont** [comment]
Time for dinner, writing down what I've learned tonight:
- This is due to a custom animation using `ZoomAnimator`; the deepest cause of the bug that I've reached so far is that the `fromReferenceView` in `animateZoomInTransition` is not found by tag for some reason, and `ZoomAnimator`'s `animateZoomInTransition` method exits early.
- Disabling the animation by changing `animated: true` to `animated: false` in the `viewModel.imagePresentations.sink` closure in `ProfileViewController.viewDidLoad` bypasses the bug.
- The intent is to zoom from the avatar or header `UIImageView` in `AccountHeaderView` (displayed inside `ProfileViewController`, a subclass of `TableViewController`) to a full-screen version in an `ImageViewController`.
- They're both looked up by tag; the tag (an integer value) is set to a hash of the image URL.
- Any code that sets a tag based on an image URL is therefore suspect.

**Comment by VyrCossont** [comment]
- I changed the avatar and header URL functions of `AccountViewModel` in the offending patch: specifically, they're now optionals. (The GtS-related change in 7ae4eb722288d60eb5931c0d0a37320ad32b8fd2 is that some GtS calls related to blocked users can return empty media URLs, so we have to be able to handle cases where an URL string doesn't decode into a valid `URL`.)
- The code setting the tags on the avatar and header images in `AccountHeaderView` did not change in the offending commit. It's not unwrapping the `URL?` into an `URL` when it sets the tag to that URL's `hashValue`.
- And the final insight: `URL` and `URL?` are different types with different hash values.

Setting the image view tags based on an unwrapped `URL` seems like it fixes the issue. Will wrap this up later.

Never use tags, kids. Definitely don't do whatever happened here. Just use explicit references to things.

**Comment by bdube** [comment]
Build 58 resolves this for me on iOS 16.5.1 (c) 🎉

**Comment by trisrc** [comment]
Yes, thanks for your good work! 🎉
