### ISSUE TITLE
Feature: Add ability to change app accent color

### ISSUE THREAD

**Issue by belatedly** [feditext/feditext#157]
**Is your feature request related to a problem? Please describe.**
Not a problem, but the standard blue is uncomfortable to look at as it reminds me of html pages without css applied lol

**Describe the solution you'd like**
Allow users to set RGB or hex codes to replace the blue accent throughout the UI

**Describe alternatives you've considered**
Having different app themes would be an alternative, but I believe that'd be more labor intensive

**Additional context**
N/A

**Comment by VyrCossont** [comment]
Doable: https://developer.apple.com/documentation/xcode/specifying-your-apps-color-scheme

Setting the accent color _per account_ seems like a potentially useful feature that'd need a bit more work. Especially for me, since I'm routinely logged into a dozen accounts with approximately the same avatar and keep forgetting where I am.

**Comment by belatedly** [comment]
Awesome! That's actually what I do on Toot!, I am terrible with checking which account I'm on and the colors help lol

**Comment by VyrCossont** [comment]
This one's getting bumped up because with this many test accounts, I really do forget which account I'm logged into on a regular basis. We'll start by allowing the user to select from the preset SwiftUI colors, which are already set up to look good in both dark and light mode.

A distant future version might get a full color picker with light mode and dark mode previews, as well as the option to extract the "hot track color" ([The Old New Thing](https://devblogs.microsoft.com/oldnewthing/20111206-00/?p=8963), [Superuser](https://superuser.com/questions/730804/how-does-windows-7-calculate-the-color-to-use-for-taskbar-color-hot-tracking), [Quora](https://www.quora.com/Google-Chrome/How-does-Chrome-pick-the-color-for-the-stripes-on-the-Most-visited-page-thumbnails-Its-clearly-based-on-the-favicon-but-I-cant-tell-exactly-how-its-derived)) from the user's avatar or instance's favicon. (This is not a high priority, I just think it'd be cute.)

**Comment by VyrCossont** [comment]
Implemented in 1.7.2 build 70.
