### ISSUE TITLE
Add optional settings for account drives (when applicable)

### ISSUE THREAD

**Issue by ghost** [feditext/feditext#199]
**Is your feature request related to a problem? Please describe.**
I don't like that I have to leave the app to access my Firefish account drive.

**Describe the solution you'd like**
A section in the settings that appears if the account is on software that support account drives (i.e. Misskey and its forks)

**Describe alternatives you've considered**
A direct link to the drive in the settings, when applicable.

**Additional context**
...

**Comment by VyrCossont** [comment]
This would be a large chunk of new work, since we currently don't use the Misskey API at all, and have no drive-like UI to reuse. If Firefish takes off, I'll consider adding Firefish-specific features like this and antennas in a later release.

If Firefish *really* takes off, I've always wanted to implement a [file provider extension](https://developer.apple.com/documentation/fileprovider/)…

Meanwhile, adding a quick access link to the relevant part of the Firefish web UI is definitely possible.

**Comment by ghost** [comment]
I am definitely asking a lot, maybe _for now_ just add links?
