### ISSUE TITLE
Two accounts, wrong credentials 

### ISSUE THREAD

**Issue by AtUser47** [feditext/feditext#258]
I have two accounts I manage with Feditext. 

When I choose the option to configure preferences I get a note that Feditext wants to use my instance to login, which is correct.

When agreeing, it logs in with the credentials of the account I was not in when I went to preferences. 

**To Reproduce**
1. Have two accounts, A & B
3. Have account B open
4. Go to preferences, agree to let fedi login
5. See account A’s detail used to login 

**Expected behavior**
Expect credentials for account pulled up in fedi to be passed along.

**Additional context**
For a beta this has been an amazingly stable project. I was so excited to finally find a problem haha. Nice work folks

**Comment by VyrCossont** [comment]
Which Fedi server are you using? Mastodon and some others have a login prompt screen that shows you the account you're logged in with and lets you log out and/or switch to a different user. This is a workaround but might get you unblocked.

The multi-account story is a bit annoying right now because it shares credentials with Safari for convenience but most Fedi servers can only handle one logged-in user per browser.

**Comment by VyrCossont** [comment]
Same issue as #217.
