### ISSUE TITLE
`hr` black on black

### ISSUE THREAD

**Issue by mirabilos** [feditext/feditext#282]
**Describe the bug**
`hr` tags (`----` in Markdown) are rendered as black on black.

**To Reproduce**
1. Post `foo\n\n----\n\nbar` on a GotoSocial instance with Markdown enabled
2. See your own post have a larger distance than normal between the paragraphs but no line

**Expected behavior**
A line, centred, perhaps 85–90% width, perhaps in lightgrey (`#AAAAAA`), on the black background of the post.

**Screenshots**
Can do if needed, ping me so.

**(please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 15.7.9 (and about to update…)
 - App Version: 1.7.2 (76)

**Additional context**
I suspect nōn-dark-mode users get a black line, which would be proper for them.

**Comment by VyrCossont** [comment]
We don't render `<hr>` at all yet because WebKit (our current HTML parser) doesn't seem to include them in `NSAttributedString` output. The Siren HTML parser is specifically aware of `<hr>` and should be able to handle them in the near future.

Note for *non*-GtS users finding this bug: Mastodon drops `<hr>` tags entirely. Not sure about other servers.

**Comment by daenney** [comment]
@tsmethurst filed a request with Masto in https://github.com/mastodon/mastodon/issues/28593 to allow `hr` through. It would be awesome if Feditext could render it too eventually.

**Comment by VyrCossont** [comment]
Siren renders `<hr>` now.
