### ISSUE TITLE
See relevent posts/toots when you click a Trending Link on the Explore tab

### ISSUE THREAD

**Issue by FueledxJarritos** [feditext/feditext#284]
**Is your feature request related to a problem? Please describe.**
I love seeing the trending links on the explore tab, but would love to see what people are saying about them instead of just opening the link

**Describe the solution you'd like**
When a Trending Link is clicked on the Explore tab, make the link/thumbnail at the top of the page with posts/toots that also contain the link(or replies to posts that contain the link)

**Comment by VyrCossont** [comment]
This would be nice to have, but unfortunately it's limited by server functionality: the Mastodon API doesn't provide a way to get a list of related posts for a trending link. Nor can we use the search API to work around it, since Mastodon proper has a search query parser bug that prevents searching for URLs.
