### ISSUE TITLE
Render MFM

### ISSUE THREAD

**Issue by Seirdy** [feditext/feditext#297]
**Is your feature request related to a problem? Please describe.**
Feditext does not currently render MFM.

**Describe the solution you'd like**
Well, this is complex.

Feditext could render static FMFM with a button to play animations.

For parsing, there's a Rust [libmfm](https://git.joinfirefish.org/firefish/libmfm) library and JS implementations used in Akko-FE (limited) and the *keys. Rendering will be tricky.

**Describe alternatives you've considered**
A more prominent link specifically for MFM posts to view the posts on the remote instance.

**Comment by VyrCossont** [comment]
We're not going to support MFM unless it becomes wildly popular by whole-Fediverse standards. Personally, I think MFM is an awful idea. It's a huge amount of work to enable features that mostly duplicate HTML formatting for a tiny fraction of the user base and are morally equivalent to `<marquee>` otherwise. Also, every Misskey fork insists on adding their own crap to it so they can make icons wiggle slightly differently, so it's also a moving target.

Tactically, Feditext is pure Swift and uses only SwiftPM packages, which are mostly also Swift (the exceptions being C or Obj-C). We're not going to take a dependency on a Rust or JS library, since it'd complicate packaging and debugging. In any case, you're correct that parsing is the easy part; rewriting our text-rendering components to support arbitrary animated text transforms would be a lot more work.

Misskey converts all incoming remote posts to MFM, so the approach I've been suggesting for Misskey fork maintainers interested in providing a Mastodon-compatible API is for the server to render MFM to HTML as best it can, and serve that through the Mastodon API. This is the route Iceshrimp went.

_Akkoma_ shouldn't have this problem at all, since it stores remote posts in the original AP format, which would almost always include HTML. I'm not sure how it handles local MFM posts, but it must have the capability to render them to HTML for federation somewhere.
