### ISSUE TITLE
AddIdentityError

### ISSUE THREAD

**Issue by Aut-B** [feditext/feditext#312]
**Describe the Bug**

It occurred while one's trying to log in some instance, such as pawoo.net or wxw.moe 
here is the code
```json
{
  "alertLocation" : {
    "file" : "ViewModels/AddIdentityViewModel.swift",
    "function" : "addIdentity(kind:)",
    "line" : 111
  },
  "app" : {
    "build" : "79",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "message" : "为了向所有用户提供安全的体验并遵守App Store 审核准则，该实例不可用。",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.6.1"
  },
  "title" : "AddIdentityError",
  "type" : "AddIdentityError"
}
```

**To Reproduce**
1. Go to 'account'
2. Click on 'add new account'
3. Input 'wxw.moe'or'pawoo.net'

**Expected behavior**

**Screenshots**

**(please complete the following information):**
 - Device: [e.g. iPhone 14]
 - OS: [e.g. iOS 16.6.1]
 - App Version [e.g. 1.7.2]

**Additional context**

**Comment by VyrCossont** [comment]
This is not a bug. Read the message. The English version of that string is "In order to provide a safe experience to all users and comply with the App Store Review Guidelines, this instance is not supported." Feditext (and Metatext before it) will not connect to a short list of instances known for illegal content (including CSAM), hate speech, and/or harassment campaigns.
