### ISSUE TITLE
App crashes often on switching tabs or loading posts

### ISSUE THREAD

**Issue by horaceyoung** [feditext/feditext#339]
**Describe the bug**
The recent build has a very high chance of crashing on loading contents or switching tabs. The root reason is unclear. I have sent crash reports for some of the crashes I experienced.

**To Reproduce**
There's no definitive trigger but the crash often happens when loading posts after clicking "show more"

**Screenshots**

**(please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17.2.1
 - App Version 1.7.2 (build 80)

**Comment by bdube** [comment]
Thank you for the report.

Multiple crash reports are pointing at this same line so I'll attach the screenshot to this issue.

![Screenshot 2024-01-06 at 8 45 57 PM](https://github.com/feditext/feditext/assets/640240/804de53a-20bc-4d3a-8a14-44e993e12b76)

**Comment by VyrCossont** [comment]
I get this bug very rarely in the simulator and thought it was simulator-specific, but that's clearly not the case. I suspect it's a timing-related bug and that we shouldn't be invoking WebKit from a `static let`. The immediate fix is to just hardcode it to 12, since I haven't seen that value change in several OS releases, and I can do that now.

The full fix is to remove it along with the rest of the WebKit-based parsing.

**Comment by VyrCossont** [comment]
Pushed the likely fix. Built fine, but one of two post-build pushes to TestFlight failed with a message indicating that it's Apple's fault, so I'll just try again.

> Beta app review submission failed (An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/.)

**Comment by VyrCossont** [comment]
Since this bug only leaves crash reports as evidence and I can't *reliably* trigger it in the simulator, it may be a while before we can confirm that it's fixed. Hopefully we'll see those crash reports drop to zero eventually.

**Comment by VyrCossont** [comment]
No recent reports of this crash site.
